

     <div id="ModalOrganizacionAsoc" class="modal  fade" >

      <div class="modal-dialog">
            <div class="modal-content">
            
    
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>

    <h4  align="center" id="Titulo">Informaci&oacute;n</h4>

    </div>
    <div class="modal-body" >
        <h4>Informaci&oacute;n General</h4>
            <div class="informacionOrganizacionselected">        
            </div>
        <h4>Departamentos</h4>
            <div class="informacionDepartamentos">        
            </div>
    </div>  
    <div class="modal-footer">
    <button  class="btn btn-default" data-dismiss="modal" aria-hidden="true"><strong>Cerrar</strong>
    </button>
  
    </div>
                
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->