<?php
session_start();

if(isset($_SESSION['id_perfil'])){
$id_perfil=$_SESSION['id_perfil'];
$nombre_perfil=$_SESSION['nombre_perfil'];
$nombre_organizacion =  $_SESSION['nombre_instituto'];
$nombre_persona = $_SESSION['persona'];
$ID_INSTITUCION=$_SESSION['ID_INSTITUCION'];

}else { 
$id_perfil=1;
$nombre_perfil="Menu Principal";
}
?>

<!DOCTYPE html>
<!-- saved from url=(0066)http://vadikom.github.io/smartmenus/src/demo/bootstrap-navbar.html -->
<html lang="en"><head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Estudiante</title>


  
 <!--   Mensajes-->

    <link rel="stylesheet" href="../js/dist/css/amaran.min.css">
    <link rel="stylesheet" href="../js/dist/css/animate.min.css">
   
   <!--  FIN  Mensajes-->
      <!--    MENU CUERPO-->
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap.min22.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap-theme.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap-responsive.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/sticky-footer-navbar.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/bootstrap-menu/dist/css/bootstrap-submenu.min.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/bootstrap-menu/dist/css/docs.css">

  <!-- Bootstrap JS -->
<script src="../../../Menus/bootstrap/js/jquery-1.11.3.min.js" ></script>
 
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/bootstrap.js" defer=""></script>
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/highlight.min.js" defer=""></script>
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/bootstrap-submenu.js" defer=""></script>
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/docs.js" defer=""></script>

  
        <link rel="stylesheet" href="../../Modulo_Estado/js/sweetalert-master/lib/sweet-alert.css">
   <script type="text/javascript" src="../../Modulo_Estado/js/sweetalert-master/lib/sweet-alert.js"></script>
   <script type="text/javascript" src="../../Modulo_Estado/js/sweetalert-master/lib/sweet-alert.min.js"></script>
  
    <!-- Placed at the end of the document so the pages load faster -->
 
    <link rel="stylesheet" href="../js/dist/css/amaran.min.css">
    <link rel="stylesheet" href="../js/dist/css/animate.min.css">


  </head>

  <body style="padding-top: 20px;">

    
<!--inicio del menu -->

<?php



include("../../../BASE_DATOS/Conect.php");
$conexionBD = new Conexion();
$conexionBD->Conectar();
include("../../Modulo_Usuario/modelo/mod_usuario.php");
$persona= new usuarios();

    if($id_perfil== 1){
      $persona->menu($id_perfil , $nombre_perfil , '','' );
    }
    else
    {
      $persona->menu($id_perfil , $nombre_perfil , $nombre_organizacion ,$nombre_persona );
    }


?>


<input type="hidden" id="codigo_estudiante" value="<?php echo $_SESSION['codigo_estudiante'] ?>">
<!-- Fin De MENU-->
<div align="center"> 
<div style="width:90%">
            <table class="table table-bordered"  >
            <tr class="well">
            <td><h4 align="center"> Organizaciones</h4></td>
            </tr>
            </table>
            <div class="tabbable" id="superdiv" style="margin-bottom: 18px;">
                <ul class="nav nav-tabs" id="pestana"></ul>

                <div class="tab-content"  style="padding-bottom: 9px; border-bottom: 1px solid #ddd;">

                </div>
            </div>
</div>
</div>
<div align="center">
        <div style="width:80%">


            

                        
        </div>
</div>

  
        
    <div id="temporadas" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
            <div class="modal-dialog modal-lg">
            <div class="modal-content">
    
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title" align="center">Temporadas de Solicitud a las que Pertenesco</h4>
    </div>
    <div class="modal-body" align="center">
    
          
            <!--TABLA DE LOS REGISTROS-->
            <div class="table-responsive">
            <table class="table table-striped table-hover dt-responsive nowrap compact"  id="tabla-temporadas" style="cursor: pointer; width:100% ">

                      
              <thead>
                        <tr >   
                              <th hidden></th>                    
                              <th> Encargado Temporada</th>
                              <th> Tipo Solicitud</th>
                              <th> Periodo Solicitud</th>
                              <th> Lapso Académico</th>
                              <th></th>
                              
                        </tr>
              </thead>



            </table>
            </div>

    </div>  
    <div class="modal-footer">
    <button  class="btn btn-default" data-dismiss="modal" aria-hidden="true"><strong>Cerrar</strong>
    </button>
    <button  class="btn btn-primary btn-large"  id="enviaSolicitud" ><strong>Enviar Postulación</strong>
    </button>
    
    <input type="hidden" id="organizacion">
    </div>
    </div>
    </div>
    </div>



  <!-- Estilo De Selects Very Good -->

<link rel="stylesheet" href="../../../Menus/bootstrap/bootstrap-select/css/jquery.selectBoxIt.css">
<script src="../../../Menus/bootstrap/bootstrap-select/js/jquery-ui-1.8.23.custom.min.js" defer=""></script> 
<script src="../../../Menus/bootstrap/bootstrap-select/js/jquery.selectBoxIt.min.js" defer=""></script>

  <!-- Estilo De Selects Very Good -->
    
      
    <script src="../../Modulo_tipoOrganizacion/js/js_tabla/media/js/jquery.dataTables.min.js"></script>
    <script src="../../Modulo_tipoOrganizacion/js/js_tabla/media/js/dataTables.bootstrap.min.js"></script> 
    <script src="../../Modulo_tipoOrganizacion/js/js_tabla/media/js/dataTables.responsive.min.js"></script> 
    <script src="../../Modulo_tipoOrganizacion/js/js_tabla/media/js/responsive.bootstrap.min.js"></script> 

    <link rel="stylesheet" href="../../../Menus/bootstrap/css/selectBien.css">
    <link href="../../Modulo_tipoOrganizacion/js/js_tabla/media/css/jquery.dataTables_themeroller.css" rel="stylesheet">
    <link href="../../Modulo_tipoOrganizacion/js/js_tabla/media/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="../../Modulo_tipoOrganizacion/js/js_tabla/media/css/responsive.bootstrap.min.css" rel="stylesheet"> 


     <script>
  $(document).ready(function(){
  
$('#tabla-temporadas').dataTable({

  "language": {
        "sProcessing":    "Procesando...",
        "sLengthMenu":    '_MENU_ Registros', // Mostrar _MENU_ registros
        "sZeroRecords":   "No se encontraron Resultados",
        "sEmptyTable":    "Ningún dato disponible en esta tabla",
        "sInfo":          "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
        "sInfoEmpty":     "Mostrando registros del 0 al 0 de un total de 0 registros",
        "sInfoFiltered":  "(filtrado de un total de _MAX_ registros)",
        "sInfoPostFix":   "",
        "sSearch":        "Buscar:",
        "sUrl":           "",
        "sInfoThousands":  ",",
        "sLoadingRecords": "Cargando...",
        "oPaginate": {
            "sFirst":    "Primero",
            "sLast":    "Último",
            "sNext":    "Siguiente",
            "sPrevious": "Anterior"
        },
        "oAria": {
            "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
            "sSortDescending": ": Activar para ordenar la columna de manera descendente"
        }
    }

      

  });
  });

</script>
    <script src="../js/dist/js/jquery.amaran.min.js"></script>
    <script src="../js/dist/js/jquery.amaran.js"></script>
  <script type="text/javascript" src="../js/postulacion.js"></script>
</body></html>
