<?php
session_start();

if(isset($_SESSION['id_perfil'])){
$id_perfil=$_SESSION['id_perfil'];
$nombre_perfil=$_SESSION['nombre_perfil'];


$nombre_organizacion =  $_SESSION['codigo_sucursal'];
$nombre_persona = $_SESSION['persona'];

}else { 
$id_perfil=1;
$nombre_perfil="Menu Principal";
}
?>

<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <title> Pasantias </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">

        <meta http-equiv="X-UA-Compatible" content="IE=edge">


    <title>Pasantias</title>

 <!--   Mensajes-->

    <link rel="stylesheet" href="../js/dist/css/amaran.min.css">
    <link rel="stylesheet" href="../js/dist/css/animate.min.css">



  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap.min22.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap-theme.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap-responsive.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/sticky-footer-navbar.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/bootstrap-menu/dist/css/bootstrap-submenu.min.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/bootstrap-menu/dist/css/docs.css">

  <!-- Bootstrap JS -->
<script src="../../../Menus/bootstrap/js/jquery-1.11.3.min.js" ></script>
 
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/bootstrap.js" defer=""></script>
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/highlight.min.js" defer=""></script>
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/bootstrap-submenu.js" defer=""></script>
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/docs.js" defer=""></script>
  
    <link rel="stylesheet" href="../../Modulo_Estado/js/sweetalert-master/lib/sweet-alert.css">
   <script type="text/javascript" src="../../Modulo_Estado/js/sweetalert-master/lib/sweet-alert.js"></script>
   <script type="text/javascript" src="../../Modulo_Estado/js/sweetalert-master/lib/sweet-alert.min.js"></script>
 

      </head>
  
  <body style="padding-top: 20px;" id="body">

<!--inicio del menu -->

<?php

include("../../../BASE_DATOS/Conect.php");
$conexionBD = new Conexion();
$conexionBD->Conectar();
include("../../Modulo_Usuario/modelo/mod_usuario.php");
$persona= new usuarios();

    $nombre_organizacion= $persona->buscar_nombre_organizacion($nombre_organizacion);

    if($id_perfil== 1){
      $persona->menu($id_perfil , $nombre_perfil , '','' );
    }
    else
    { 
      
      $persona->menu($id_perfil , $nombre_perfil , $_SESSION['nombre_organizacion'] ,$nombre_persona );
    }


?>

<!-- Fin De MENU-->
<div align="center">
        <div style="width:80%">
	
		<table class="table table-bordered" width="90" >
			<tr  class="well"><td>
				<h4 align="center">Solicitudes Realizadas</h4>
			</td></tr> 
		</table>
<input type="hidden" id="codigo_sucursal" value="<?php  echo $_SESSION['codigo_sucursal']?>">
<input type="hidden" id="ID_PERSONA" value="<?php  echo $_SESSION['id_persona']?>">

			<table class="display dataTable" id="mitavle" style="cursor:pointer">
	
				<thead><tr>
                <td><center><strong>Instituto</strong></center></td>
                
				<td><center><strong>Fecha </strong></center></td>				
				<td width="20"><center><strong>Cantidad</strong></center></td>
                <td><center><strong>Realizada Por</strong></center></td>
                <td><center><strong>Área</strong></center></td>
				<td width="50"><center><strong>Detalles</strong></center></td>
                <td width="50"><center><strong>Postulados</strong></center></td>
                <td style="display:none"><center><strong>codigo</strong></center></td>
				
				</tr></thead> 
			
		    </table>

	


           </div>               
</div >

<?php include('ModalsS.phtml') ?>

     <!--PAGINADOR-->
         <script src="../../Modulo_tipoOrganizacion/js/js_tabla/media/js/jquery.dataTables.js"></script>
    <script src="../../Modulo_tipoOrganizacion/js/js_tabla/media/js/jquery.dataTables.min.js"></script>

    <link href="../../Modulo_tipoOrganizacion/js/js_tabla/media/css/jquery.dataTables.css" rel="stylesheet">
    <link href="../../Modulo_tipoOrganizacion/js/js_tabla/media/css/jquery.dataTables.min.css" rel="stylesheet">
    <link href="../../Modulo_tipoOrganizacion/js/js_tabla/media/css/jquery.dataTables_themeroller.css" rel="stylesheet">

   <script type="text/javascript" src="../js/solicitudver.js"></script>
   
  </body>
</html>
