<?php
session_start();

if(isset($_SESSION['id_perfil'])){

  $id_perfil           = $_SESSION['id_perfil'];

  $nombre_perfil       = $_SESSION['nombre_perfil'];  
  
  $nombre_organizacion = $_SESSION['nombre_instituto'];

  $nombre_persona      = $_SESSION['persona'];

  $id_instituto        = $_SESSION['ID_INSTITUCION'];

}else { 
  $id_perfil     =1;
  $nombre_perfil ="Menu Principal";
}
?>
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <title> Pasantias </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">

        <meta http-equiv="X-UA-Compatible" content="IE=edge">



    

      <!--    MENU CUERPO-->
       
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap.min22.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap-theme.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap-responsive.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/sticky-footer-navbar.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/bootstrap-menu/dist/css/bootstrap-submenu.min.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/bootstrap-menu/dist/css/docs.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap.vertical-tabs.min.css">

  <!-- Bootstrap JS -->
<script src="../../../Menus/bootstrap/js/jquery-1.11.3.min.js" ></script>
 
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/bootstrap.js" defer=""></script>
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/highlight.min.js" defer=""></script>
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/bootstrap-submenu.js" defer=""></script>
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/docs.js" defer=""></script>
  

      </head>
  
  <body style="padding-top: 20px;" id="body">

<!--inicio del menu -->

<?php

include("../../../BASE_DATOS/Conect.php");
$conexionBD = new Conexion();
$conexionBD->Conectar();
include("../../Modulo_Usuario/modelo/mod_usuario.php");
$persona= new usuarios();

    if($id_perfil== 1){
      $persona->menu($id_perfil , $nombre_perfil , '','' );
    }
    else
    { 
      echo '<input type=hidden id=id_ip value='.$id_instituto.' >';
      echo '<label hidden id=codigo_encargado>'.$_SESSION['codigo_encargado'].'</label >';
      
      $persona->menu($id_perfil , $nombre_perfil , $nombre_organizacion ,$nombre_persona );
    }
?>

<!-- Fin De MENU-->
<div align="center">
	<table width="90%">
	  <tr>
		<td>
        	
			<table class="table table-bordered">
			  	<tr class="well">
					<td>
                    	<h4><center>Organizaciones Asociadas</center></h4>
					</td>
			  	</tr>
			</table>
         

                <div class="row">
                  <div class="col-xs-3" >
                  <ul class="nav nav-pills tabs-left" id="pestana"></ul>
                  </div>
                  <div class="col-xs-8" >
                  <div class="tab-content"  style="padding-bottom: 9px; border-bottom: 1px solid #ddd;">
                  </div>
                  </div>
                </div>
           


                          
</div >
<?php include('modalOrganizacionesAsociadas.html') ?>
   
  <!-- Estilo De Selects Very Good -->

<link rel="stylesheet" href="../../../Menus/bootstrap/bootstrap-select/css/jquery.selectBoxIt.css">
<script src="../../../Menus/bootstrap/bootstrap-select/js/jquery-ui-1.8.23.custom.min.js" defer=""></script> 
<script src="../../../Menus/bootstrap/bootstrap-select/js/jquery.selectBoxIt.min.js" defer=""></script>

  <!-- Estilo De Selects Very Good -->   

     <!--PAGINADOR-->
    <script src="../../Modulo_tipoOrganizacion/js/js_tabla/media/js/jquery.dataTables.min.js"></script>
    <script src="../../Modulo_tipoOrganizacion/js/js_tabla/media/js/dataTables.bootstrap.min.js"></script> 
    <script src="../../Modulo_tipoOrganizacion/js/js_tabla/media/js/dataTables.responsive.min.js"></script> 
    <script src="../../Modulo_tipoOrganizacion/js/js_tabla/media/js/responsive.bootstrap.min.js"></script> 

    <link rel="stylesheet" href="../../../Menus/bootstrap/css/selectBien.css">
    <link href="../../Modulo_tipoOrganizacion/js/js_tabla/media/css/jquery.dataTables_themeroller.css" rel="stylesheet">
    <link href="../../Modulo_tipoOrganizacion/js/js_tabla/media/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="../../Modulo_tipoOrganizacion/js/js_tabla/media/css/responsive.bootstrap.min.css" rel="stylesheet"> 




   <script src="../js/MisOrganizaciones.js" ></script>

  </body>
</html>
