<?php
session_start();

if(isset($_SESSION['id_perfil'])){
$id_perfil=$_SESSION['id_perfil'];
$nombre_perfil=$_SESSION['nombre_perfil'];
$nombre_organizacion =  $_SESSION['nombre_instituto'];
$nombre_persona = $_SESSION['persona'];
$ID_INSTITUCION=$_SESSION['ID_INSTITUCION'];
}else { 
$id_perfil=1;
$nombre_perfil="Menu Principal";
}
?>

<!DOCTYPE html>
<!-- saved from url=(0066)http://vadikom.github.io/smartmenus/src/demo/bootstrap-navbar.html -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Pasantias</title>


  <!--    MENU CUERPO-->

  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap.min22.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap-theme.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap-responsive.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/sticky-footer-navbar.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/bootstrap-menu/dist/css/bootstrap-submenu.min.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/bootstrap-menu/dist/css/docs.css">

  <!-- Bootstrap JS -->
  <script src="../../../Menus/bootstrap/js/jquery-1.10.2.min.js"></script>
  
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/bootstrap.js" defer=""></script>
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/highlight.min.js" defer=""></script>
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/bootstrap-submenu.js" defer=""></script>
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/docs.js" defer=""></script>
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../js/js/jquery.js"></script>
    <script src="../js/js/bootstrap-transition.js"></script>
    <script src="../js/js/bootstrap-alert.js"></script>
    <script src="../js/js/bootstrap-modal.js"></script>
    <script src="../js/js/bootstrap-dropdown.js"></script>
    <script src="../js/js/bootstrap-scrollspy.js"></script>
    <script src="../js/js/bootstrap-tab.js"></script>
    <script src="../js/js/bootstrap-tooltip.js"></script>
    <script src="../js/js/bootstrap-popover.js"></script>
    <script src="../js/js/bootstrap-button.js"></script>
    <script src="../js/js/bootstrap-collapse.js"></script>
    <script src="../js/js/bootstrap-carousel.js"></script>
    <script src="../js/js/bootstrap-typeahead.js"></script>
  
 

  <script language='javascript' src="../js/validaciones.js"></script> 


  </head>

  <body style="padding-top: 20px;">

    
<!--inicio del menu -->

<?php

include("../../../BASE_DATOS/Conect.php");
$conexionBD = new Conexion();
$conexionBD->Conectar();
include("../../Modulo_Usuario/modelo/mod_usuario.php");
$persona= new usuarios();

    if($id_perfil== 1){
      $persona->menu($id_perfil , $nombre_perfil , '','' );
    }
    else
    {
      $persona->menu($id_perfil , $nombre_perfil , $nombre_organizacion ,$nombre_persona );
    }
?>

<!-- Fin De MENU-->

<div align="center">
        <div style="width:60%">
        <table class="table table-bordered">
          <tr class="well">
              <td><h4 align="center">Gestion De Usuario Tutor Académico</h4></td>
            </tr>
          <tr>
            <td>
                  <center>
                <form name="form" action="../controlador/ctr_estudiante.php" method="post" onsubmit="return validar_registro_estudiante()" >
                          
                            <div class="row-fluid">
                              <div class="span6">
                                    <?php echo ' <input type="hidden" id="" name="id_persona" value="'.$_SESSION['id_persona'].'">'?>
                                    <?php echo ' <input type="hidden" id="" name="id_usuario" value="'.$_SESSION['id_usuario'].'">'?>
                                      <input type="hidden"name="id_instituto" id="id_instituto" value="<?php echo $_SESSION['ID_INSTITUCION']; ?>">
                            
                                    <strong>Código:</strong><br>
                                    <?php echo '<input type="text" id="expediente" name="espediante" value="'.$_SESSION['expediente'].'" autocomplete="off" required disabled>'?>
                                    <font color="red" size="4">*</font><br>   
                                    <strong>Cédula:</strong><br>
                                    <?php echo '<input type="text" id="cedula" name="cedula" value="'.$_SESSION['cedula_persona'].'" autocomplete="off" required disabled> '?> 
                                    <font color="red" size="4">*</font><br>  
                                    <strong>Nombre:</strong><br>
                                    <?php echo '<input type="text" id="nombre" name="nombre" value="'.$_SESSION['nombre_persona'].'" autocomplete="off" required disabled>'?>
                                    <font color="red" size="4">*</font><br>
                                    <strong>Apellido:</strong><br>
                                    <?php echo '<input type="text" id="apellido" name="apellido" value="'.$_SESSION['apellido_persona'].'" autocomplete="off" disabled>'?>
                                    <font color="red" size="4">*</font><br>
                                    <strong>Especialidad:</strong><br>
                                    <?php echo '<input type="text" id="" name="angle" value="'.$_SESSION['especialidad'].'" autocomplete="off" disabled>'?>
                                    <font color="red" size="4">*</font><br>  
                                </div>
                              <div class="span6">

                                    <strong>Fecha de Asignación:</strong> &nbsp;<br>
                        <?php echo '<input type="Date" id="fecha" name="fecha" value="'.$_SESSION['fecha_solicitud'].'" autocomplete="off"  required onkeyup="this.value=this.value.toUpperCase()">' ?>
                                    <font color="red" size="4">*</font> 
                          <br>
                                    <strong>Telefono:</strong><br> 
                                    <?php echo '<input type="text" id="telefono"  name="telefono" onkeypress="return numeros(event);" maxlength="11" value="'.$_SESSION['telefono'].'" autocomplete="off" >'?>
                                    <font color="red" size="4">*</font><br> 
                                 
                                    <strong>Correo:</strong><br>  
                                    <?php echo '<input type="email" name="correo" id="correo" onkeyup="this.value=this.value.toUpperCase()"  value="'.$_SESSION['correo'].'" autocomplete="off" >'?>
                                    <font color="red" size="4">*</font><br>  
                                
                                    <strong>Usuario:</strong><br>
                                    <?php echo '<input type="text" name="usuario" id="usuario" onkeyup="ConsultaUsuarios(this.value)" onkeyup="this.value=this.value.toUpperCase()"  value="'.$_SESSION['usuario'].'" autocomplete="off" '?>
                                    <font color="red" size="4">*</font>  
                                    <div id="usuario"></div>
                                 
                                    <strong>Contraseña:</strong><br>  
                                    <?php echo '<input type="password" name="contrasena_a" id="contrasena_a" onkeypress="return numeros(event);" maxlength="15" value="'.$_SESSION['contrasena'].'" autocomplete="off" >'?>
                                    <font color="red" size="4">*</font>
                                    <br>
                                 
                                    <strong>Repita Contraseña:</strong><br>  
                                    <?php echo '<input type="password" name="contrasena_b" id="contrasena_b"  onkeypress="return numeros(event);"  maxlength="15" value="'.$_SESSION['contrasena'].'" autocomplete="off" >'?>
                                      <font color="red" size="4">*</font>
                                    <br>
                                    
                                </div>
                            </div><br>
                            <center> 

                            <?php echo ' <input  name="botRegistrar" type="submit" value="Registrar" class="btn btn-primary btn-large" style="'.$_SESSION['ocultar_r'].'"> '?>
                               <?php echo ' <input  name="botModificar" type="submit" value="Modificar" class="btn btn-primary btn-large"  style="'.$_SESSION['ocultar_m'].'">'?>
                           </center>
                                <div align="right">
                              <a href="consultar_usuario_estudiante.phtml"><input type="button" value="Atras"class="btn btn-primary btn-large"></a>
                               </div>
                        </form>
                        <font color="red" size="2">(*) </font><font color="red" size="1">Campos Obligatorios... </font>
                    </center>
                </td>
          </tr>
        </table>
    </div></div>
      

  
           <!--   Mensajes-->
 <script src="../js/dist/js/jquery.amaran.min.js"></script>
 <script src="../js/dist/js/jquery.amaran.js"></script>
   <!--  FIN  Mensajes-->
  
</body></html>
