<?php
session_start();

if(isset($_SESSION['id_perfil'])){
$id_perfil=$_SESSION['id_perfil'];
$nombre_perfil=$_SESSION['nombre_perfil'];
$nombre_organizacion =  $_SESSION['nombre_instituto'];
$nombre_persona = $_SESSION['persona'];
$ID_INSTITUCION=$_SESSION['ID_INSTITUCION'];
}else { 
$id_perfil=1;
$nombre_perfil="Menu Principal";
}
?>
<!DOCTYPE html>
<!-- saved from url=(0066)http://vadikom.github.io/smartmenus/src/demo/bootstrap-navbar.html -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Pasantias</title>

 <!--   Mensajes-->

    <link rel="stylesheet" href="../js/dist/css/amaran.min.css">
    <link rel="stylesheet" href="../js/dist/css/animate.min.css">
   
   <!--  FIN  Mensajes-->


  <!--    MENU CUERPO-->

  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap.min22.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap-theme.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/bootstrap-responsive.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/css/sticky-footer-navbar.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/bootstrap-menu/dist/css/bootstrap-submenu.min.css">
  <link rel="stylesheet" href="../../../Menus/bootstrap/bootstrap-menu/dist/css/docs.css">

  <!-- Bootstrap JS -->
  <script src="../../../Menus/bootstrap/js/jquery-1.10.2.min.js"></script>
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/bootstrap.js" defer=""></script>
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/highlight.min.js" defer=""></script>
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/bootstrap-submenu.js" defer=""></script>
  <script src="../../../Menus/bootstrap/bootstrap-menu/dist/js/docs.js" defer=""></script>
  
   <link rel="stylesheet" href="../js/sweetalert-master/lib/sweet-alert.css">
  <script type="text/javascript" src="../js/sweetalert-master/lib/sweet-alert.js"></script>
   <script type="text/javascript" src="../js/sweetalert-master/lib/sweet-alert.min.js"></script>

  <script language='javascript' src="../js/validaciones.js"></script> 






  </head>

  <body style="padding-top: 20px;">

    
<!--inicio del menu -->

<?php

include("../../../BASE_DATOS/Conect.php");
$conexionBD = new Conexion();
$conexionBD->Conectar();
include("../../Modulo_Usuario/modelo/mod_usuario.php");
$persona= new usuarios();

    if($id_perfil== 1){
      $persona->menu($id_perfil , $nombre_perfil , '','' );
    }
    else
    {
      $persona->menu($id_perfil , $nombre_perfil , $nombre_organizacion ,$nombre_persona );
    }
?>

<!-- Fin De MENU-->

<div align="center">
        <div style="width:60%">
        <table class="table table-bordered">
          <tr class="well">
              <td><h4 align="center">Gestión De Tutor Académico</h4></td>
            </tr>
          <tr>
            <td>
                  <center>
                <form name="form" action="../controlador/ctr_estudiante.php" method="post" onsubmit="return validar_registro_estudiante()" >
                          
                            <div class="row-fluid">
                              <div class="span6">
                                   
                                    <input type="hidden" id="id_instituto_asignar" name="id_usuario" value="<?php echo $ID_INSTITUCION; ?>">
                                    <input type="hidden" id="id_persona" name="id_persona" value="">

                                    <strong>Código:</strong> &nbsp;<br>
                                    <input type="text"   id="expediente" name="espediante" placeholder="CODIGO" onkeyup='busqueda_expediente()' value="" autocomplete="off" required onkeyup="this.value=this.value.toUpperCase() "  maxlength="5"onkeypress="return numeros(event);">
                                    <font color="red" size="4">*</font> 
                          <br> 

                                    <strong>Cédula:</strong> &nbsp;<br>
                                    <input type="text" min="0" max="99999999" id="cedula" name="cedula" placeholder="CÉDULA" onkeyup='busqueda_cedula()' value="" autocomplete="off" required onkeyup="this.value=this.value.toUpperCase()" maxlength="8" onkeypress="return numeros(event);">
                                    <font color="red" size="4">*</font> 
                          <br>

                                    <strong>Nombre:</strong> &nbsp;<br>
                                    <input type="text" maxlength="20" id="nombre_e" name="nombre" placeholder="NÓMBRE" value="" autocomplete="off" required onkeyup="this.value=this.value.toUpperCase()" onkeypress="return letras(event);">
                                    <font color="red" size="4">*</font> 
                          <br>

                                    <strong>Apellido:</strong> &nbsp;<br>
                                    <input type="text" maxlength="20" id="apellido_e" name="apellido" placeholder="APELLIDO" value="" autocomplete="off" required onkeyup="this.value=this.value.toUpperCase()" onkeypress="return letras(event);">
                                    <font color="red" size="4">*</font> 
                          <br>
                              </div>
                              <div class="span6">
                              
                              

                                    <strong>Observación:</strong> &nbsp;<br>
                                    <textarea id="observacion" maxlength="200" name="observacion" placeholder="ESCRIBA UNA BREVE DESCRIPCIÓN..." value="" autocomplete="off" required onkeyup="this.value=this.value.toUpperCase()"></textarea>
                                    <font color="red" size="4">*</font> 
                          <br>

                                    <strong>Especialidad:</strong><br>
                                     <select id="id_especialidad" name="id_especialidad" required>
                                              
                                              <option value=""  >SELECCIONE...</option>
                                              <?php 
                                                include("../modelo/mod_estudiante.php");
                                                $estudiante= new estudiante();
                                                $estudiante->llenarselectEspecialidad($ID_INSTITUCION);
                                              ?>
                                              

                                            </select>
                                            <font color="red" size="4">*</font> 
                                    
                                </div>
                              
                                
                            </div>
                            <center> 
                       <input   type="button" id="Registrar" name="botRegistrar" value="Registrar" class="btn btn-primary btn-large">
                       <input   type="button" id="Modificar" name="botModificar" value="Modificar" disabled="" class="btn btn-primary btn-large">
                       <input   type="button" id="Eliminar" name="botEliminar" value="Eliminar" disabled="" class="btn btn-primary btn-large">
                       <input   type="button" id="Cancelar" name="botCCancelar" value="Cancelar" class="btn btn-primary btn-large">     
                           </center>
                        </form>
                  
                  <font color="red" size="2">(*) </font><font color="red" size="1">Campos Obligatorios... </font>
              
                    </center>
                </td>
          </tr>
        </table>
    </div>
    </div>
    


<div align="center">
  <table width="70%">
    <tr>
    <td>
          
      <table class="table table-bordered"  >
          <tr class="well">
          <td>
                      <center><strong>Personas Registradas</strong></center>
          </td>
          </tr>
      </table>
            
           
          
            
            <!--TABLA DE LOS REGISTROS-->
            <table class="table table-bordered" id="Table" width="100%">
               
             

            		<?php
                 $estudiante->cargarcatalogoPersonas($ID_INSTITUCION);
               
                 	?>
               
    

            </table>
    </td>
    </tr>
  </table>
</div>


<!--PAGINADOR-->
    <script src="../js/js_tabla/jquery.dataTables.js"></script>
    <script>
    $(document).ready(function(){
      $('#Table').dataTable();
    });
  </script>
    <script src='../js/js_tabla/tablesort.min.js'></script>

  <script>
      new Tablesort(document.getElementById('table-id'));
    </script>
     <link href="../js/js_tabla/jquery.dataTables.css" rel="stylesheet">
  
<script src='../js/estudiante.js'></script>
         <!--   Mensajes-->
 <script src="../js/dist/js/jquery.amaran.min.js"></script>
 <script src="../js/dist/js/jquery.amaran.js"></script>
   <!--  FIN  Mensajes-->
</body></html>
