<?php
session_start();

if(isset($_SESSION['id_perfil'])){
      $id_perfil=$_SESSION['id_perfil'];
      $nombre_perfil=$_SESSION['nombre_perfil'];
      $nombre_organizacion =  $_SESSION['nombre_instituto'];
      $nombre_persona = $_SESSION['persona'];
}else { 
      $id_perfil=1;
      $nombre_perfil="Menu Principal";
}
?>
  <!DOCTYPE html>
<!-- saved from url=(0066)http://vadikom.github.io/smartmenus/src/demo/bootstrap-navbar.html -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Pasantias</title>



        <!--   Mensajes-->

    <link rel="stylesheet" href="../js/dist/css/amaran.min.css">
    <link rel="stylesheet" href="../js/dist/css/animate.min.css">
    
      <!--    MENU CUERPO-->
    <link href="../../../Menus/menu_estilo/css/bootstrap.css" rel="stylesheet">
    <link href="../../../Menus/menu_estilo/css/bootstrap-responsive.css" rel="stylesheet">
    <script src="../../../Menus/menu_estilo/css/menu/menu_files/jquery-1.10.2.min.js"></script>
    
<!--   MENU ARRIBA-->
    <link href="../../../Menus/menu_estilo/css/menu/bootstrap.min.css" rel="stylesheet">
    <link href="../../../Menus/menu_estilo/css/menu/smartmenus.bootstrap.css" rel="stylesheet"> 


<!-- Bootstrap core JavaScript
    ================================================== -->
<!--    STILOS TABLAS-->
      <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../../../Menus/menu_estilo/css/menu/menu_files/jquery-1.11.2.min.js"></script>
    <script src="../../../Menus/menu_estilo/css/menu/menu_files/bootstrap.min.js"></script>
    <script src="../js/tablallena.js"></script>
    <!-- SmartMenus jQuery plugin -->
    <script type="text/javascript" src="../../../Menus/menu_estilo/css/menu/menu_files/jquery.smartmenus.js"></script>
    <!-- SmartMenus jQuery Bootstrap Addon -->
    <script type="text/javascript" src="../../../Menus/menu_estilo/css/menu/menu_files/jquery.smartmenus.bootstrap.js"></script>
  

  </head>



  <body  style="padding-top: 20px;">
    
<!--inicio del menu -->

<?php

include("../../../BASE_DATOS/Conect.php");
$conexionBD = new Conexion();
$conexionBD->Conectar();
include("../../Modulo_Usuario/modelo/mod_usuario.php");
$persona= new usuarios();
    if($id_perfil== 1){
      $persona->menu($id_perfil , $nombre_perfil , '','' );
    }
    else
    {
      $persona->menu($id_perfil , $nombre_perfil , $nombre_organizacion ,$nombre_persona );
    }
?>

<!-- Fin De MENU-->

<div align="center">
    
    <div style="width:60%">




            <table class="table table-bordered">
            <tr class="well">
            <td><h4 align="center">Gesti&oacute;n Tipo Solicitud</h4></td>
            </tr>
            </table>


              <div class="tabbable" style="margin-bottom: 18px;">
              <ul class="nav nav-tabs">

        <li class="active"><a href="#tab1" id="tipo_solicitud" data-toggle="tab"><strong>Tipo de Solicitud</strong></a></li>
       
        <li class="<?php ?>"><a href="#tab3" data-toggle="tab"><strong>Requisito</strong></a></li>
        
              </ul>
              <div class="tab-content" style="padding-bottom: 9px; border-bottom: 1px solid #ddd;">
              <div class="tab-pane active" id="tab1">
              <div class="row-fluid">

        <table class="table table-bordered">
              <tr class="well">
              <td><h4 align="center">Registrar Tipo Solicitud:<p id="titlee" ></p></h4></td>
              </tr>
              <tr>
              <td>
                        <center>
                          
                            <div class="row-fluid">
                              <div class="span6">
                              
                  <!--   <strong>Seleccionar Instituto Principal:   </strong>  
                    <a href="#tabla_Instituto" id="buscarRegistrios" role="button" class="btn btn-primary" data-toggle="modal">Buscar</a><br><br>
                    <input type="hidden" id="superidOrganizacion" name="organizacion" value="" autocomplete="off" required>  -->                               
                                <strong>Nombre Tipo Solicitud:</strong><br>
                                <textarea id="nombre_tipo_solicitud" value="" autocomplete="off" required> </textarea>   <br>
                                <strong>Estatus:</strong><br>
                                <select id="estatus" required >
                                <option value="">ACTIVO</option>
                                <option value="">INACTIVO</option>
                                </select><br>
                                </div>
                                </div>
                            </div><br>
                          <center> 
                            <input type="submit" id="Registrar_Tipo_Solicitud"  value="Registrar" class="btn btn-primary btn-large">
                            
                             </center>

                    </center>
                </td>
                </tr>
                </table>


                </div>
                  
                </div>



                <div class="tab-pane " id="tab3">
                      <table class="table table-bordered">
          <tr class="well">

              <td><h4 align="center">Requisito:<p id="titlee_pepple" ></p> </h4></td>
            </tr>
          <tr>
            <td>
                  <center>
                        
              
              <div class="row-fluid">
               <!--  <div class="col-md-6">-->           
              <div class="span6">
              
            <strong>Buscar Tipo Solicitud:   </strong>  
            <a href="#" id="tablaTipo_Solicitud" role="button" class="btn btn-primary" data-toggle="modal">Buscar</a><br>
            
             <input type="hidden" id="id_tipo_solicitud" name="nombre" value="" autocomplete="off" required>

              
            <strong>Requisito:</strong><br>
            <input type="text"  id="requisito" value="" autocomplete="off" required  maxlength="40" >  <br> 
            <strong>Estatus:</strong><br>
                                <select id="estatus" required >
                                <option value="">ACTIVO</option>
                                <option value="">INACTIVO</option>
                                </select><br>

          </div>
          </div> <br>

                    <center> 
                    <input id="Requisito" name="botRegistrar" type="submit" value="Registrar" class="btn btn-primary btn-large">
                  
                    </center>

                            
          </center>  

                                    
                              
                    
                </td>
          </tr>
        </table>

        </div>
        </div>

    </div></div>
      

  

    <script src="../js/js/jquery.js"></script>
    <script src="../js/js/bootstrap-transition.js"></script>
    <script src="../js/js/bootstrap-alert.js"></script>
    <script src="../js/js/bootstrap-modal.js"></script>
    <script src="../js/js/bootstrap-dropdown.js"></script>
    <script src="../js/js/bootstrap-scrollspy.js"></script>
    <script src="../js/js/bootstrap-tab.js"></script>
    <script src="../js/js/bootstrap-tooltip.js"></script>
    <script src="../js/js/bootstrap-popover.js"></script>
    <script src="../js/js/bootstrap-button.js"></script>
    <script src="../js/js/bootstrap-collapse.js"></script>
    <script src="../js/js/bootstrap-carousel.js"></script>
    <script src="../js/js/bootstrap-typeahead.js"></script>

    <!-- Le javascript ../../js/jquery.js
    
    onchange="pais(this.value);"
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
 
    <!--  EL MODAL DE LA PERSONA -->

       <div id="tabla_Tipo_Solicitud" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

    
    <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3  align="center">Elije un Tipo de Solicitud<br></h3>

    </div>
    <div class="modal-body" align="center">
    <table width="110%">
    <tr>
    <td>
          

            <!--TABLA DE LOS REGISTROS-->
            <table class="table table-bordered"  id="tabla-Tipo_Solicitud">


            </table>
    </td>
    </tr>
    </table>

    </div>  
    <div class="modal-footer">
    <button  class="btn" data-dismiss="modal" aria-hidden="true"><strong>Cerrar</strong>
    </button>
  
    </div>
    </div>
  


  <script src="../js/js_tabla/jquery.dataTables.js"></script>
  <script src="../../../Menus/menu_estilo/css/menu/menu_files/jquery-1.11.2.min.js"></script>
  <link href="../js/js_tabla/jquery.dataTables.css" rel="stylesheet">
  
  <script src="../js/dist/js/jquery.amaran.min.js"></script>
  <script src="../js/dist/js/jquery.amaran.js"></script>
  <!--<script src="../js/institucionConvenio.js"></script>
  // <script src="../js/PersonaConvenio.js"></script>
  // <script src="../js/autoComplete.js"></script>-->
  <script>
  $(document).ready(function(){
  $('#myTable').dataTable();
  
  $('#tabla-Tipo_Solicitud').dataTable();
  $('#TablaRequisito').dataTable();
  });
  </script>

  
  <!-- JS de los Mensajes COOL Very Preatty -->

  <script src='../js/js_tabla/tablesort.min.js'></script>

  <script>
      new Tablesort(document.getElementById('table-id'));

  </script>

  <!-- Esta es mi js  que  utiliza  todos los  que  estan alla  arriba ! XD -->

  <!-- src="../js/PersonaEncargada.js" -->



</body></html>
